workflows:
  ios-testflight:
    name: iOS TestFlight (signed)
    max_build_duration: 60
    integrations:
      app_store_connect: "ASC"   # EXACT name from Teams → Integrations
    environment:
      xcode: latest
      node: 20
    scripts:
      - name: Install deps & sync Capacitor
        script: |
          set -e
          npm ci
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          set -e
          cd ios/App
          pod install --repo-update
      - name: Fetch signing files
        script: |
          set -e
          app-store-connect fetch-signing-files "org.greystreet.app" --type IOS_APP_STORE --create
          xcode-project use-profiles
      - name: Build signed IPA
        script: |
          set -euo pipefail
          cd ios/App
          xcode-project build-ipa --workspace App.xcworkspace --scheme App --archive-flags="-destination 'generic/platform=iOS'"
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
