workflows:
  ios-simulator-build:
    name: Build for iOS Simulator (Appetize)
    max_build_duration: 60
    environment:
      xcode: latest
      node: 20
    scripts:
      - name: Install deps & build web + sync Capacitor
        script: |
          set -e
          npm ci
          npm run build
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          set -e
          cd ios/App
          pod install --repo-update
      - name: Build (iphonesimulator, Debug) to fixed path
        script: |
          set -euo pipefail
          cd ios/App
          xcodebuild -list -workspace App.xcworkspace
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath $PWD/build \
            build
          ls -la "$PWD/build/Build/Products" || true
          ls -la "$PWD/build/Build/Products/Debug-iphonesimulator" || true
      - name: Zip simulator .app for Appetize
        script: |
          set -e
          APP_PATH=$(find ios/App/build -type d -name "*.app" -path "*/Build/Products/*-iphonesimulator/*" | head -n 1 || true)
          if [ -z "$APP_PATH" ]; then
            APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -type d -name "*.app" -path "*/Build/Products/*-iphonesimulator/*" | head -n 1 || true)
          fi
          if [ -z "$APP_PATH" ]; then
            echo "ERROR: No simulator .app found."
            exit 1
          fi
          echo "Found simulator app at: $APP_PATH"
          cd "$(dirname "$APP_PATH")"
          zip -r Appetize-sim.zip "$(basename "$APP_PATH")"
    artifacts:
      - ios/App/build/Build/Products/*-iphonesimulator/*.app
      - ios/App/build/Build/Products/*-iphonesimulator/Appetize-sim.zip
      - ~/Library/Developer/Xcode/DerivedData/**/Build/Products/*-iphonesimulator/*.app
      - ~/Library/Developer/Xcode/DerivedData/**/Build/Products/*-iphonesimulator/Appetize-sim.zip

  ios-device-build:
    name: Build for iOS Device (unsigned)
    max_build_duration: 60
    environment:
      xcode: latest
      node: 20
    scripts:
      - name: Install deps & build web + sync Capacitor
        script: |
          set -e
          npm ci
          npm run build
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          set -e
          cd ios/App
          pod install --repo-update
      - name: Build (iphoneos, Release) unsigned
        script: |
          set -euo pipefail
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -derivedDataPath $PWD/build \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
            build
          ls -la "$PWD/build/Build/Products" || true
          ls -la "$PWD/build/Build/Products/Release-iphoneos" || true
    artifacts:
      - ios/App/build/Build/Products/Release-iphoneos/*.app

  ios-testflight:
    name: iOS TestFlight (signed)
    max_build_duration: 60
    integrations:
      app_store_connect: "ASC"   # <-- replace with your EXACT integration name if different
    environment:
      xcode: latest
      node: 20
    scripts:
      - name: Install deps & build web + sync Capacitor
        script: |
          set -e
          npm ci
          npm run build
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          set -e
          cd ios/App
          pod install --repo-update
      - name: Fetch signing files
        script: |
          set -e
          app-store-connect fetch-signing-files "org.greystreet.app" --type IOS_APP_STORE --create
          xcode-project use-profiles
      - name: Build signed IPA
        script: |
          set -euo pipefail
          cd ios/App
          xcode-project build-ipa --workspace App.xcworkspace --scheme App --archive-flags="-destination 'generic/platform=iOS'"
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
      email:
        recipients:
          - patobrien2017@gmail.com