workflows:
  ios-simulator-build:
    name: Build for iOS Simulator
    max_build_duration: 60
    environment:
      xcode: latest
      node: 20
    scripts:
      - name: Install deps & sync Capacitor
        script: |
          npm ci
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update
      - name: Build (iphonesimulator, Debug)
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            CODE_SIGNING_ALLOWED=NO | xcpretty
      - name: Zip simulator .app for Appetize
        script: |
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -path "*/Build/Products/Debug-iphonesimulator/*.app" | head -n 1)
          echo "Found simulator app at: $APP_PATH"
          cd "$(dirname "$APP_PATH")"
          # zip so that the .app is at the ZIP ROOT (what Appetize requires)
          zip -r Appetize-sim.zip "$(basename "$APP_PATH")"
    artifacts:
      - ~/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphonesimulator/*.app
      - ~/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphonesimulator/Appetize-sim.zip
    publishing:
      email:
        recipients:
          - patobrien2017@gmail.com
