workflows:
  ios-adhoc:
    name: iOS Ad Hoc (direct device install)
    max_build_duration: 60
    integrations:
      app_store_connect: "ASC"
    environment:
      xcode: latest
      node: 20
      groups:
        - ios_signing1     # needs: P12_BASE64, P12_PASSWORD, PROFILE_ADHOC_BASE64
      vars:
        BUNDLE_ID: "org.greystreet.app"
        PROFILE_ADHOC_NAME: "GreyStreet_AdHoc_Profile"
        DEVELOPMENT_TEAM: "J5K98H247G"
    scripts:
      - name: Install deps & build web + sync Capacitor
        script: |
          set -e
          npm ci
          npm run build
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          set -e
          cd ios/App
          pod install --repo-update

      - name: Write signing files from env (Ad Hoc)
        script: |
          set -e
          mkdir -p $CM_BUILD_DIR/signing
          if [ -z "${P12_BASE64:-}" ] || [ -z "${PROFILE_ADHOC_BASE64:-}" ]; then
            echo "ERROR: Missing P12_BASE64 or PROFILE_ADHOC_BASE64 in group ios_signing1"
            exit 1
          fi
          echo "$P12_BASE64"           | base64 --decode > $CM_BUILD_DIR/signing/cert.p12
          echo "$PROFILE_ADHOC_BASE64" | base64 --decode > $CM_BUILD_DIR/signing/${PROFILE_ADHOC_NAME}.mobileprovision

      - name: Import certificate to keychain
        script: |
          set -e
          KEYCHAIN=build.keychain
          KEYCHAIN_PATH=~/Library/Keychains/${KEYCHAIN}-db
          security create-keychain -p "" "$KEYCHAIN"
          security unlock-keychain -p "" "$KEYCHAIN"
          security set-keychain-settings -lut 21600 "$KEYCHAIN"
          security list-keychains -s "$KEYCHAIN"
          security default-keychain -s "$KEYCHAIN"
          security import $CM_BUILD_DIR/signing/cert.p12 -k "$KEYCHAIN" -P "$P12_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security
          security set-key-partition-list -S apple-tool:,apple: -s -k "" "$KEYCHAIN"
          echo "KEYCHAIN_PATH=$KEYCHAIN_PATH" > $CM_BUILD_DIR/keychain_path.env

      - name: Install Ad Hoc profile & wire to App target (Pods stay Automatic)
        script: |
          set -e
          PROFILE_SRC="$CM_BUILD_DIR/signing/${PROFILE_ADHOC_NAME}.mobileprovision"
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp "$PROFILE_SRC" ~/Library/MobileDevice/Provisioning\ Profiles/
          TMP_PLIST="$CM_BUILD_DIR/adhoc.plist"
          security cms -D -i "$PROFILE_SRC" > "$TMP_PLIST"
          APP_ID=$(/usr/libexec/PlistBuddy -c 'Print:Entitlements:application-identifier' "$TMP_PLIST" 2>/dev/null || echo "")
          case "$APP_ID" in
            *"$BUNDLE_ID") ;;
            *) echo "ERROR: Ad Hoc profile app id ($APP_ID) doesn't match $BUNDLE_ID"; exit 1 ;;
          esac
          # Wire profile to App target only
          xcode-project use-profiles

      - name: Ensure Pods have NO provisioning profile (scrub Pods project)
        script: |
          set -e
          PBX="ios/App/Pods/Pods.xcodeproj/project.pbxproj"
          cp "$PBX" "$PBX.bak" || true
          # Remove any explicit provisioning profile specifier lines in Pods
          /usr/bin/sed -i '' '/PROVISIONING_PROFILE_SPECIFIER = /d' "$PBX" || true
          # Force Pods code sign style to Automatic (if any Manual slipped in)
          /usr/bin/sed -i '' 's/CODE_SIGN_STYLE = Manual;/CODE_SIGN_STYLE = Automatic;/g' "$PBX" || true
          echo "Scrubbed Pods provisioning settings."

      - name: Clean before build
        script: |
          set -e
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release clean

      - name: Bump build number (timestamp)
        script: |
          set -e
          BUILD_TS=$(date -u +%Y%m%d%H%M%S)
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_TS" ios/App/App/Info.plist
          echo "CFBundleVersion set to $BUILD_TS"

      - name: Archive (manual signing for App only)
        script: |
          set -euo pipefail
          source $CM_BUILD_DIR/keychain_path.env
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath $PWD/build/App.xcarchive \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=${DEVELOPMENT_TEAM} \
            PRODUCT_BUNDLE_IDENTIFIER=${BUNDLE_ID} \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            OTHER_CODE_SIGN_FLAGS="--keychain $KEYCHAIN_PATH" \
            archive

      - name: Export Ad Hoc IPA (map profile only for app bundle id)
        script: |
          set -e
          cd ios/App
          cat > exportOptions.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>teamID</key>
              <string>J5K98H247G</string>
              <key>provisioningProfiles</key>
              <dict>
                <key>org.greystreet.app</key>
                <string>GreyStreet_AdHoc_Profile</string>
              </dict>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
            </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath $PWD/build/App.xcarchive \
            -exportOptionsPlist $PWD/exportOptions.plist \
            -exportPath $PWD/build/export

      - name: Print where your IPA is
        script: |
          set -e
          ls -la ios/App/build/export
          echo "Ad Hoc IPA ready at ios/App/build/export/"

    artifacts:
      - ios/App/build/export/*.ipa
      - ios/App/build/export/*.dSYM.zip

    publishing:
      email:
        recipients:
          - patobrien2017@gmail.com