workflows:
  ios-dev-clean:
    name: iOS Development (clean export)
    max_build_duration: 60
    environment:
      xcode: latest
      node: 20
      vars:
        BUNDLE_ID: "org.greystreet.app"
        DEVELOPMENT_TEAM: "J5K98H247G"
        IOS_WORKSPACE: "App.xcworkspace"
        IOS_SCHEME: "App"
        DEV_PROFILE_NAME: "GreyStreet_Dev_Profile"
    scripts:
      - name: Install deps, build web, sync Capacitor
        script: |
          set -e
          npm ci
          npm run build
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          set -e
          cd ios/App
          pod install --repo-update

      - name: Bump build number & clean
        script: |
          set -e
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $(date -u +%Y%m%d%H%M%S)" ios/App/App/Info.plist
          cd ios/App
          xcodebuild -workspace "$IOS_WORKSPACE" -scheme "$IOS_SCHEME" -configuration Debug clean

      - name: Archive (UNSIGNED to avoid Pods signing)
        script: |
          set -euo pipefail
          cd ios/App
          xcodebuild \
            -workspace "$IOS_WORKSPACE" \
            -scheme "$IOS_SCHEME" \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            -archivePath "$PWD/build/AppDev.xcarchive" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            SKIP_INSTALL=NO \
            archive

      - name: Create exportOptions.plist (development)
        script: |
          set -e
          PLIST_PATH="ios/App/exportOptions.dev.plist"
          rm -f "$PLIST_PATH"
          # Create a fresh root dict
          /usr/libexec/PlistBuddy -c 'Add : dict' "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c 'Add :method string development' "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c 'Add :signingStyle string manual' "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c 'Add :teamID string J5K98H247G' "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c 'Add :destination string export' "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c 'Add :signingCertificate string Apple Development' "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c 'Add :stripSwiftSymbols bool true' "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c 'Add :compileBitcode bool false' "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c 'Add :manageAppVersionAndBuildNumber bool false' "$PLIST_PATH"
          # Map profile ONLY to the app bundle id
          /usr/libexec/PlistBuddy -c 'Add :provisioningProfiles dict' "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Add :provisioningProfiles:${BUNDLE_ID} string ${DEV_PROFILE_NAME}" "$PLIST_PATH"
          echo "=== exportOptions.dev.plist (xml) ==="
          plutil -convert xml1 "$PLIST_PATH" -o -
          echo "=== plutil -lint ==="
          plutil -lint "$PLIST_PATH"

      - name: Export Development IPA (xcodebuild)
        script: |
          set -euo pipefail
          cd ios/App
          xcodebuild -exportArchive \
            -archivePath "$PWD/build/AppDev.xcarchive" \
            -exportPath "$PWD/build/dev_export" \
            -exportOptionsPlist "$PWD/exportOptions.dev.plist"
          echo "=== Exported files ==="
          ls -la "$PWD/build/dev_export"

      - name: Sanity print (embedded profile UUID + devices)
        script: |
          set -e
          IPA="ios/App/build/dev_export/App.ipa"
          TMP="$(mktemp -d)"
          cp "$IPA" "$TMP/App.zip"
          unzip -q "$TMP/App.zip" -d "$TMP/unz"
          PROV="$TMP/unz/Payload/App.app/embedded.mobileprovision"
          echo "=== Dev Profile UUID ==="
          /usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< "$(security cms -D -i "$PROV")" || true
          echo "=== Provisioned Devices (first few) ==="
          /usr/libexec/PlistBuddy -c 'Print :ProvisionedDevices' /dev/stdin <<< "$(security cms -D -i "$PROV")" 2>/dev/null | head -n 20 || echo "No devices list"

    artifacts:
      - ios/App/build/dev_export/*.ipa
      - ios/App/build/AppDev.xcarchive
      - ios/App/exportOptions.dev.plist

    publishing:
      email:
        recipients:
          - patobrien2017@gmail.com