workflows:
  ios-capacitor-build:
    name: iOS Capacitor Build
    max_build_duration: 60
    environment:
      xcode: latest
      node: 20
    scripts:
      - name: Install deps & sync Capacitor
        script: |
          npm ci
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update
      - name: Build iOS app (no signing)
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""
    artifacts:
      - ios/App/build/**/*.app
    publishing:
      email:
        recipients:
          - patobrien2017@gmail.com
