workflows:
  ios-capacitor-build:
    name: iOS Capacitor Build
    max_build_duration: 60
    environment:
      xcode: latest
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          npm ci
          node -v
          npm -v
      - name: Sync Capacitor for iOS
        script: |
          npx cap sync ios
      - name: Build iOS app (no signing)
        script: |
          cd ios/App
          xcodebuild -scheme App -sdk iphoneos -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    artifacts:
      - ios/App/build/**/*.app
    publishing:
      email:
        recipients:
          - patobrien2017@gmail.com
