workflows:
  ios-simulator-build:
    name: Build for iOS Simulator
    max_build_duration: 60
    environment:
      xcode: latest
      node: 20
    scripts:
      - name: Install deps & sync Capacitor
        script: |
          set -e
          npm ci
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          set -e
          cd ios/App
          pod install --repo-update
      - name: Build (iphonesimulator, Debug) to fixed path
        script: |
          set -e
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -derivedDataPath $PWD/build \
            CODE_SIGNING_ALLOWED=NO | xcpretty
      - name: Zip simulator .app for Appetize
        script: |
          set -e
          echo "=== Listing known build locations ==="
          echo "-> ios/App/build:"
          ls -la ios/App/build || true
          echo "-> ios/App/build/Build/Products:"
          ls -la ios/App/build/Build/Products || true
          echo "-> DerivedData Products:"
          ls -la ~/Library/Developer/Xcode/DerivedData/*/Build/Products 2>/dev/null || true

          # Try fixed build path first
          APP_PATH=$(find ios/App/build -type d -name "*.app" -path "*/Build/Products/*-iphonesimulator/*" | head -n 1 || true)

          # Fallback to DerivedData if not found
          if [ -z "$APP_PATH" ]; then
            APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -type d -name "*.app" -path "*/Build/Products/*-iphonesimulator/*" | head -n 1 || true)
          fi

          if [ -z "$APP_PATH" ]; then
            echo "ERROR: No simulator .app found. Check xcodebuild logs above."
            exit 1
          fi

          echo "Found simulator app at: $APP_PATH"
          APP_DIR="$(dirname "$APP_PATH")"
          APP_NAME="$(basename "$APP_PATH")"
          cd "$APP_DIR"
          zip -r Appetize-sim.zip "$APP_NAME"
    artifacts:
      - ios/App/build/Build/Products/*-iphonesimulator/*.app
      - ios/App/build/Build/Products/*-iphonesimulator/Appetize-sim.zip
      - ~/Library/Developer/Xcode/DerivedData/**/Build/Products/*-iphonesimulator/*.app
      - ~/Library/Developer/Xcode/DerivedData/**/Build/Products/*-iphonesimulator/Appetize-sim.zip
publishing:
      email:
        recipients:
          - patobrien2017@gmail.com
